# Generated by Django 3.1.1 on 2023-04-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pic/profilepic.jpg', upload_to='profile_pic'),
        ),
    ]
